mavlink stream -d /dev/ttyS4 -s ALTITUDE -r 10
mavlink stream -d /dev/ttyS4 -s ATTITUDE -r 100
mavlink stream -d /dev/ttyS4 -s ATTITUDE_QUATERNION -r 50
mavlink stream -d /dev/ttyS4 -s ATTITUDE_TARGET -r 10
mavlink stream -d /dev/ttyS4 -s CURRENT_EVENT_SEQUENCE -r 0
mavlink stream -d /dev/ttyS4 -s ESTIMATOR_STATUS -r 1
mavlink stream -d /dev/ttyS4 -s EXTENDED_SYS_STATE -r 5
mavlink stream -d /dev/ttyS4 -s HEARTBEAT -r 1
mavlink stream -d /dev/ttyS4 -s HIGHRES_IMU -r 50
mavlink stream -d /dev/ttyS4 -s LINK_NODE_STATUS -r 1
mavlink stream -d /dev/ttyS4 -s LOCAL_POSITION_NED -r 30
mavlink stream -d /dev/ttyS4 -s MISSION_CURRENT -r 1
mavlink stream -d /dev/ttyS4 -s ODOMETRY -r 30
mavlink stream -d /dev/ttyS4 -s OPEN_DRONE_ID_LOCATION -r 1
mavlink stream -d /dev/ttyS4 -s PING -r 1
mavlink stream -d /dev/ttyS4 -s POSITION_TARGET_LOCAL_NED -r 10
mavlink stream -d /dev/ttyS4 -s SCALED_PRESSURE -r 1
mavlink stream -d /dev/ttyS4 -s SYSTEM_TIME -r 1
mavlink stream -d /dev/ttyS4 -s SYS_STATUS -r 4
mavlink stream -d /dev/ttyS4 -s TIMESYNC -r 10
mavlink stream -d /dev/ttyS4 -s GPS_RAW_INT -r 5
mavlink stream -d /dev/ttyS4 -s HOME_POSITION -r 1
mavlink stream -d /dev/ttyS4 -s GLOBAL_POSITION_INT -r 50